name: "CGLab @ "
description: "Webpage of the Comparative Genomics Lab at the Institute of Molecular Biology and Biotechnology in Crete"

url: "https://cgenomicslab.org"

paginate: 5
plugins: [jekyll-paginate]
paginate_path: "news/page:num"

permalink: pretty
markdown: kramdown
kramdown:
  parse_block_html: true

exclude:
        - .sass-cache/
        - .jekyll-cache/
        - gemfiles/
        - Gemfile
        - Gemfile.lock
        - node_modules/
        - vendor/bundle/
        - vendor/cache/
        - vendor/gems/
        - vendor/ruby/

collections:
        affiliates:
                output: true
        members:
                output: true
        publications:
                output: true
        reviews:
                output: true
        alumni:
                output: true
        sep:
                output: false
        visitors:
                output: false
        undergrads:
                output: true
        pets:
                output: true
        tags:
                output: true
